version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - palworld-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - stack.env
    networks:
      - palworld-net

networks:
  palworld-net:
    driver: bridge
